### ISSUE TITLE
https://chao.fun/p/1160802 用户反馈该视频Android 不能播放

### ISSUE THREAD

**Issue by cijianzy** [www-chao-fun/chaofun-app#212]

**Comment by cijianzy** [comment]
https://chao.fun/p/1161387 补充一粒

**Comment by cijianzy** [comment]
E/LoadTask(25433): Unexpected exception loading stream
E/LoadTask(25433):   java.lang.ArrayIndexOutOfBoundsException: length=161; index=161
E/LoadTask(25433):       at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
E/LoadTask(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
E/LoadTask(25433):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/LoadTask(25433):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
E/LoadTask(25433):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
E/LoadTask(25433):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/LoadTask(25433):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/LoadTask(25433):       at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(25433): Playback error
E/ExoPlayerImplInternal(25433):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
E/ExoPlayerImplInternal(25433):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(25433):       at android.os.Looper.loop(Looper.java:207)
E/ExoPlayerImplInternal(25433):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(25433):   Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=161; index=161
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
E/ExoPlayerImplInternal(25433):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(25433):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(25433):       at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(25433):   Caused by: java.lang.ArrayIndexOutOfBoundsException: length=161; index=161
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
E/ExoPlayerImplInternal(25433):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
E/ExoPlayerImplInternal(25433):       ... 3 more

**Comment by cijianzy** [comment]
version: 2.3.0
